# Generated by Django 5.1.1 on 2025-08-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#667eea', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URL Category',
                'verbose_name_plural': 'URL Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='The short code for the URL', max_length=10, unique=True)),
                ('custom_alias', models.CharField(blank=True, help_text='Custom alias for the URL', max_length=50, null=True, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times the short URL was clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for the short URL', null=True)),
                ('title', models.CharField(blank=True, help_text='Title of the original page', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the original page')),
                ('domain', models.CharField(blank=True, help_text='Domain of the original URL', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the short URL is active')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the short URL is publicly accessible')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='shortener.urlcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortened_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='URLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('referer', models.URLField(blank=True, help_text='Referer URL', null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='mobile, desktop, tablet', max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.urlshortener')),
            ],
            options={
                'verbose_name': 'URL Click',
                'verbose_name_plural': 'URL Clicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['short_code'], name='shortener_u_short_c_dc4e31_idx'),
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['custom_alias'], name='shortener_u_custom__aba336_idx'),
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['created_at'], name='shortener_u_created_eee1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['domain'], name='shortener_u_domain_99d742_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclick',
            index=models.Index(fields=['url', 'created_at'], name='shortener_u_url_id_681eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclick',
            index=models.Index(fields=['ip_address'], name='shortener_u_ip_addr_819ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclick',
            index=models.Index(fields=['created_at'], name='shortener_u_created_5a39db_idx'),
        ),
    ]
